### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Generated)
add_subdirectory(RobotContent)
add_subdirectory(Robot)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Generated_QtQuick3D_Sceneplugin
    Generated_QtQuick3D_Flower__1_plugin
    Generated_QtQuick3D_Flowafirst__1_plugin
    Generated_QtQuick3D_Flowasecondplugin
    Generated_QtQuick3D_Flowathirdplugin
    Generated_QtQuick3D_Flowafinishedplugin
    RobotContentplugin
    Robotplugin)